phrases:[dict] = [
  {"id": 1, "phrase": "All aboard the shitshow express, I mean, happy Monday!", "category": "Monday"},
  {"id": 2, "phrase": "Mondays should come with a fucking warning label.", "category": "Monday"},
  {"id": 3, "phrase": "It’s Monday—time to slap on my 'I give a fuck' face.", "category": "Monday"},
  {"id": 4, "phrase": "Another Monday? Who the fuck approved this?", "category": "Monday"},
  {"id": 5, "phrase": "Coffee: because murder is illegal.", "category": "Monday"},
  {"id": 6, "phrase": "Monday: where productivity meets procrastination in an epic battle.", "category": "Monday"},
  {"id": 7, "phrase": "Fuck motivation, I need more sleep.", "category": "Monday"},
  {"id": 8, "phrase": "Running on caffeine and pure fucking spite.", "category": "Monday"},
  {"id": 9, "phrase": "Just a friendly reminder: I don’t fucking care today.", "category": "Monday"},
  {"id": 10, "phrase": "Monday: a tragic sequel no one asked for.", "category": "Monday"},

  {"id": 11, "phrase": "It’s only Tuesday? Fuck this.", "category": "Tuesday"},
  {"id": 12, "phrase": "Dear Tuesday, you’re not cute. Go away.", "category": "Tuesday"},
  {"id": 13, "phrase": "Tuesday is just Monday’s ugly fucking cousin.", "category": "Tuesday"},
  {"id": 14, "phrase": "Productivity? I hardly know her.", "category": "Tuesday"},
  {"id": 15, "phrase": "Today’s forecast: partly shitty with a 90% chance of more bullshit.", "category": "Tuesday"},
  {"id": 16, "phrase": "Running low on fucks. Please check back tomorrow.", "category": "Tuesday"},
  {"id": 17, "phrase": "I thought I had energy. Turns out it was just caffeine and false hope.", "category": "Tuesday"},
  {"id": 18, "phrase": "I came, I saw, I said 'fuck this' and left.", "category": "Tuesday"},
  {"id": 19, "phrase": "Tuesday’s to-do list: survive.", "category": "Tuesday"},
  {"id": 20, "phrase": "I'm already tired of this week's bullshit.", "category": "Tuesday"},

  {"id": 21, "phrase": "It’s fucking Wednesday—congratulations on making it this far.", "category": "Wednesday"},
  {"id": 22, "phrase": "The week is half over, but my patience is fully gone.", "category": "Wednesday"},
  {"id": 23, "phrase": "If Wednesday had a face, I’d punch it.", "category": "Wednesday"},
  {"id": 24, "phrase": "We’re halfway through the week and I’m still not halfway to giving a fuck.", "category": "Wednesday"},
  {"id": 25, "phrase": "I’ve officially run out of social energy. Please try again next week.", "category": "Wednesday"},
  {"id": 26, "phrase": "Why work when I could be taking a glorious fucking nap?", "category": "Wednesday"},
  {"id": 27, "phrase": "My mood: powered by sarcasm and suppressed rage.", "category": "Wednesday"},
  {"id": 28, "phrase": "The struggle is still fucking real.", "category": "Wednesday"},
  {"id": 29, "phrase": "Can I get a 'fuck yeah' for surviving this far? No? Me neither.", "category": "Wednesday"},
  {"id": 30, "phrase": "Wednesday: one step closer to freedom, one more fuck lost.", "category": "Wednesday"},

  {"id": 31, "phrase": "It’s not Friday yet? What the actual fuck?", "category": "Thursday"},
  {"id": 32, "phrase": "So close to the weekend, yet so full of bullshit.", "category": "Thursday"},
  {"id": 33, "phrase": "Just gonna power through today with the last remaining fuck I have.", "category": "Thursday"},
  {"id": 34, "phrase": "Another day, another pile of bullshit.", "category": "Thursday"},
  {"id": 35, "phrase": "My patience is on fucking backorder.", "category": "Thursday"},
  {"id": 36, "phrase": "The finish line is in sight, but my will to care is fucking gone.", "category": "Thursday"},
  {"id": 37, "phrase": "Someone hand me a drink and a reason to not quit my job.", "category": "Thursday"},
  {"id": 38, "phrase": "I’d love to stay and chat, but I fucking wouldn’t.", "category": "Thursday"},
  {"id": 39, "phrase": "Today’s energy level: nonexistent.", "category": "Thursday"},
  {"id": 40, "phrase": "Fuck this, fuck that, fuck everything.", "category": "Thursday"},

  {"id": 41, "phrase": "It’s fucking Friday, bitches!", "category": "Friday"},
  {"id": 42, "phrase": "Cheers to surviving another week of bullshit.", "category": "Friday"},
  {"id": 43, "phrase": "If Friday had a face, I’d fucking kiss it.", "category": "Friday"},
  {"id": 44, "phrase": "Friday: the only day I slightly give a fuck.", "category": "Friday"},
  {"id": 45, "phrase": "Productivity is at 2%, please plug me into the weekend.", "category": "Friday"},
  {"id": 46, "phrase": "Work? No thanks, I’m mentally out of office.", "category": "Friday"},
  {"id": 47, "phrase": "Smiling because the weekend is near, not because I like you.", "category": "Friday"},
  {"id": 48, "phrase": "Just here to collect my paycheck and fuck off.", "category": "Friday"},
  {"id": 49, "phrase": "Friday mood: zero responsibilities, maximum sarcasm.", "category": "Friday"},
  {"id": 50, "phrase": "If you need me, I’ll be fucking off into the weekend.", "category": "Friday"},

  {"id": 51, "phrase": "Saturday: the official day for ignoring people.", "category": "Saturday"},
  {"id": 52, "phrase": "Plans? Fuck no, I’m staying home.", "category": "Saturday"},
  {"id": 53, "phrase": "My weekend agenda: do nothing and love every fucking second of it.", "category": "Saturday"},
  {"id": 54, "phrase": "Outside? Sounds like a fucking nightmare.", "category": "Saturday"},
  {"id": 55, "phrase": "I came, I saw, I decided to fucking stay in.", "category": "Saturday"},
  {"id": 56, "phrase": "If you see me outside on a Saturday, mind your own fucking business.", "category": "Saturday"},
  {"id": 57, "phrase": "Introverts unite… separately, in our own homes.", "category": "Saturday"},
  {"id": 58, "phrase": "My body is here, but my soul is in bed.", "category": "Saturday"},
  {"id": 59, "phrase": "I could be social today, but that sounds fucking exhausting.", "category": "Saturday"},
  {"id": 60, "phrase": "Saturday: when my brain clocks out of adulting.", "category": "Saturday"},

  {"id": 61, "phrase": "Sunday: the day before the shit hits the fan again.", "category": "Sunday"},
  {"id": 62, "phrase": "Enjoying my last few fuck-free hours before Monday ruins everything.", "category": "Sunday"},
  {"id": 63, "phrase": "I should be productive, but nah, fuck that.", "category": "Sunday"},
  {"id": 64, "phrase": "Sunday is just Monday’s evil fucking twin.", "category": "Sunday"},
  {"id": 65, "phrase": "Mentally preparing for another week of bullshit.", "category": "Sunday"},
  {"id": 66, "phrase": "I’d rather stub my toe repeatedly than think about Monday.", "category": "Sunday"},
  {"id": 67, "phrase": "I need a weekend extension, this one was defective.", "category": "Sunday"},
  {"id": 68, "phrase": "Procrastinating my responsibilities like a fucking pro.", "category": "Sunday"},
  {"id": 69, "phrase": "Sunday night blues: brought to you by anxiety and regret.", "category": "Sunday"},
  {"id": 70, "phrase": "Can’t Monday just fucking not?", "category": "Sunday"}
]
